[package]
name = "s2"

version = "0.0.5"
authors = ["Jihyun Yu <yjh0502@gmail.com>"]

license = "Apache-2.0"

description = "S2 geometric library"
homepage = "https://github.com/yjh0502/rust-s2"
repository = "https://github.com/yjh0502/rust-s2"
documentation = "https://docs.rs/rust-s2"

keywords = ["geo", "s2"]

[dependencies]
lazy_static = "0.2"
rand = "0.3"
float_extras = "0.1"
cgmath = "0.14"

[profile.release]
debug = 2
